"""Bullpen pipeline data models.

These dataclasses represent the structured payloads passed between
agents in the bullpen pipeline. They complement the existing models
in magic_content_engine/models.py.

Requirements: REQ-4.2, REQ-6.2, REQ-8.2, REQ-9.4, REQ-10.2 (bullpen-architecture spec)
"""

from __future__ import annotations

from dataclasses import dataclass, field


# ---------------------------------------------------------------------------
# Researcher / Desk Editor models
# ---------------------------------------------------------------------------


@dataclass
class ScoredArticle:
    """A single article with relevance score from the Researcher.

    Lightweight bullpen-specific model. Maps to the existing Article
    dataclass in magic_content_engine/models.py but carries only the
    fields needed through the pipeline.
    """

    title: str
    url: str
    source: str
    relevance_score: int  # 1-5
    summary: str  # one-sentence summary generated by Researcher


@dataclass
class ResearchBrief:
    """Output of the Researcher Agent."""

    articles: list[ScoredArticle]
    sources_crawled: list[str]   # URLs attempted
    sources_failed: list[str]    # URLs that failed after retries
    run_timestamp: str           # ISO 8601


@dataclass
class ContentBrief:
    """Output of the Desk Editor Agent."""

    selected_articles: list[ScoredArticle]  # subset of ResearchBrief articles
    editorial_angle: str
    tone_guidance: str           # references voice rules from 01-niche-and-voice.md
    output_types: list[str]      # requested output type strings
    run_timestamp: str           # ISO 8601


# ---------------------------------------------------------------------------
# Writer Agent output
# ---------------------------------------------------------------------------


@dataclass
class FileEntry:
    """A single file written by the Writer Agent."""

    path: str  # relative to output/
    output_type: str  # blog, youtube, cfp, usergroup, digest
    word_count: int


@dataclass
class WriterManifest:
    """Output of the Writer Agent — lists every file it produced."""

    files_written: list[FileEntry]
    voice_rules_applied: bool = True  # always True per Writer contract
    run_timestamp: str = ""  # ISO 8601


# ---------------------------------------------------------------------------
# Subeditor Agent output
# ---------------------------------------------------------------------------


@dataclass
class Verdict:
    """Subeditor's assessment of a single content file.

    verdict is exactly one of: "publish" | "revise" | "spike"
    feedback is non-empty for revise/spike, empty string for publish.
    """

    filename: str
    verdict: str  # "publish" | "revise" | "spike"
    feedback: str  # specific feedback for revise, rationale for spike, "" for publish


@dataclass
class SubeditorReview:
    """Output of the Subeditor Agent — one Verdict per input file."""

    verdicts: list[Verdict]
    run_timestamp: str  # ISO 8601
