"""Bullpen pipeline data models.

These dataclasses represent the structured payloads passed between
agents in the bullpen pipeline. They complement the existing models
in magic_content_engine/models.py.

Requirements: REQ-4.2, REQ-6.2 (bullpen-architecture spec)
"""

from __future__ import annotations

from dataclasses import dataclass, field


@dataclass
class ScoredArticle:
    """A single article with relevance score from the Researcher.

    Lightweight bullpen-specific model. Maps to the existing Article
    dataclass in magic_content_engine/models.py but carries only the
    fields needed through the pipeline.
    """

    title: str
    url: str
    source: str
    relevance_score: int  # 1-5
    summary: str  # one-sentence summary generated by Researcher


@dataclass
class ResearchBrief:
    """Output of the Researcher Agent."""

    articles: list[ScoredArticle]
    sources_crawled: list[str]   # URLs attempted
    sources_failed: list[str]    # URLs that failed after retries
    run_timestamp: str           # ISO 8601


@dataclass
class ContentBrief:
    """Output of the Desk Editor Agent."""

    selected_articles: list[ScoredArticle]  # subset of ResearchBrief articles
    editorial_angle: str
    tone_guidance: str           # references voice rules from 01-niche-and-voice.md
    output_types: list[str]      # requested output type strings
    run_timestamp: str           # ISO 8601
